#!/usr/bin/env sh

monitor1=eDP-1-1
monitor2=HDMI-1-1


#POLYBAR
killall -q polybar
while pgrep -x polybar >/dev/null; do sleep 1; done


# Create Top/Workspaces Polybars only if monitor is connected.
HDMI_CONNECTED=$(xrandr | grep "$monitor2 connected")

if [ -z "$HDMI_CONNECTED" ]
then
	MONITOR=$monitor1 polybar -c ~/.config/polybar/polybar top &
else
	MONITOR=$monitor2 polybar -c ~/.config/polybar/polybar top &
	MONITOR=$monitor2 polybar -c ~/.config/polybar/polybar workspaces &
fi

MONITOR=$monitor1 polybar -c ~/.config/polybar/polybar workspaces &


#COMPTON
killall -q compton
while pgrep -x compton >/dev/null; do sleep 1; done
compton --glx-no-stencil --glx-no-rebind-pixmap --glx-swap-method exchange --config ~/.config/compton/compton &


#DUNST
killall -q dunst
while pgrep -x dunst >/dev/null; do sleep 1; done
dunst -config ~/.config/dunst/dunst
