#!/usr/bin/env sh

monitor1=eDP-1-1
monitor2=HDMI-1-1


# Create Top/Workspaces Polybars only if monitor is connected.

HDMI_CONNECTED=$(xrandr | grep "$monitor2 connected")

if [ -n "$HDMI_CONNECTED" ]
then
	# MONITOR=$monitor1 polybar -c ~/.config/polybar/polybar top &
	echo "THEN $HDMI_CONNECTED"
else
	# ONITOR=$monitor2 polybar -c ~/.config/polybar/polybar top &
	# ONITOR=$monitor2 polybar -c ~/.config/polybar/polybar workspaces &
	echo "ELSE $HDMI_CONNECTED"
fi

