#!/bin/bash
ROFI_OPTIONS=(-theme $HOME/.config/rofi/rofi_full -m 0 -fullscreen)

another=$(echo "Configs
Scripts
Functions
Shell" | awk '{print $(NF-1)}' | rofi "${ROFI_OPTIONS[@]}" -dmenu -i -p "SYSTEM: ")



navigate(){
	selected=$(ls "$1/" | rofi "${ROFI_OPTIONS[@]}" -dmenu -p "$1: ")
	[[ -z $selected ]] && exit
	if [[ -f $1/$selected ]]; then
		# alacritty -e vim $1/$selected
		tmux-sendkeys config "vim $1/$selected"
	elif [[ -d $1/$selected ]]; then
		navigate $1/$selected
	else
		touch $1/$selected
		# alacritty -e vim $1/$selected
		tmux-sendkeys config "vim $1/$selected"
	fi
}



if [ "$another" == "Shell" ] ; then
	selected=$(echo "$HOME/.bashrc
$HOME/.tmux.conf
$HOME/.vimrc" | rofi "${ROFI_OPTIONS[@]}" -dmenu -p "shell: ")
		[[ -z $selected ]] && exit
	# alacritty -e vim $selected
	tmux-sendkeys config "vim $selected"

elif [ "$another" == "Configs" ] ; then
	navigate /home/piero/.config;

elif [ "$another" == "Scripts" ] ; then
	navigate /home/piero/.scripts;

elif [ "$another" == "Functions" ] ; then
	navigate /home/piero/.func;

else
    echo $another
fi
