#!/bin/bash
ROFI_OPTIONS=(-theme $HOME/.config/rofi/rofi_full -m 0 -fullscreen)

another=$(echo "Configs
Scripts
Functions
Shell" | awk '{print $(NF-1)}' | rofi "${ROFI_OPTIONS[@]}" -dmenu -i -p "SYSTEM: ")



browse(){
	selected=$(ls "$1/" | rofi "${ROFI_OPTIONS[@]}" -dmenu -p "$1: ")
	[[ -z $selected ]] && exit
	if [[ -f $1/$selected ]]; then
		vim $1/$selected
	elif [[ -d $1/$selected ]]; then
		browse $1/$selected
	else
		touch $1/$selected
		chmod +x $1/$selected
		vim $1/$selected
	fi
}



if [ "$another" == "Shell" ] ; then
	selected=$(echo "$HOME/.bashrc
$HOME/.tmux.conf
$HOME/.vimrc
$HOME/.Xmodmap
$HOME/.Xdefaults" | rofi "${ROFI_OPTIONS[@]}" -dmenu -p "shell: ")
	[[ -z $selected ]] && exit
	vim $selected

elif [ "$another" == "Configs" ] ; then
	browse /home/piero/.config;

elif [ "$another" == "Scripts" ] ; then
	browse /home/piero/.scripts;

elif [ "$another" == "Functions" ] ; then
	browse /home/piero/.func;

else
    echo $another
fi
