#!/bin/bash

ROFI_OPTIONS=(-theme $HOME/.config/rofi/rofi_bar -m -1 -width 900)
ROFI_OPTIONS_FULL=(-theme $HOME/.config/rofi/rofi_full -m -1 -fullscreen)

select=$(echo "runapp
documents
websearch
sudorun" | awk '{print $(NF-1)}' | rofi "${ROFI_OPTIONS[@]}" -theme-str 'configuration{show-icons: false;}' -dmenu -i -p "search: ")


if [ "$select" == "documents" ] ; then
	FILES=$(find ~/Documents ~/Downloads -type f -not -path "*/\.*" -not -path "*/Development/*" -not -path "*/Pictures/*")
	echo "${FILES}" | rofi "${ROFI_OPTIONS[@]}" -theme-str 'configuration{show-icons: false;}' -threads 1 -dmenu -i -p 'search:' | xargs -r -0 xdg-open;

elif [ "$select" == "websearch" ] ; then
	rofi "${ROFI_OPTIONS_FULL[@]}" -dmenu -input /dev/null -p "Google:" | xargs -I % xdg-open "https://www.google.com/search?q=%"

elif [ "$select" == "runapp" ] ; then
	rofi "${ROFI_OPTIONS[@]}" -modi 'run,drun' -show drun

elif [ "$select" == "sudorun" ] ; then
	SUDO_ASKPASS=/home/piero/.scripts/askpass rofi "${ROFI_OPTIONS[@]}" -modi 'run,drun' -show drun -theme-str '*{accent: #F10F09;}' -run-command 'sudo -A {cmd}'

else
	echo "variable empty"
fi
