#!/bin/bash

ROFI_OPTIONS=(-theme $HOME/.config/rofi/rofi_bar -m 0 -width 800)

query=$(echo "runapp
documents
websearch
bookmarks
sudorun" | awk '{print $(NF-1)}' | rofi "${ROFI_OPTIONS[@]}" -dmenu -i -p "search: ")


if [ "$query" == "documents" ] ; then
	find ~/Documents/ -type f | rofi "${ROFI_OPTIONS[@]}" -threads 0 -dmenu -i -p 'search:' | xargs -r -0 xdg-open;

elif [ "$query" == "websearch" ] ; then
    xdg-open https://www.google.com/search?q=$query

elif [ "$query" == "bookmarks" ] ; then
	exec ~/.config/rofi/menu/marks;

elif [ "$query" == "runapp" ] ; then
	rofi "${ROFI_OPTIONS[@]}" -modi 'run,drun' -show drun

elif [ "$query" == "sudorun" ] ; then
	SUDO_ASKPASS=/home/piero/.scripts/askpass rofi "${ROFI_OPTIONS[@]}" -modi 'run,drun' -show drun -theme-str '*{accent: #F10F09;}' -run-command 'sudo -A {cmd}'

else
	echo "variable empty"
fi
