#!/bin/bash

ROFI_OPTIONS=(-theme $HOME/.config/rofi/rofi_full -m 0 -fullscreen)

another=$(echo "RELOAD
LOCK
LOGOUT
SUSPEND
REBOOT
POWEROFF" | awk '{print $(NF-1)}' | rofi "${ROFI_OPTIONS[@]}" -dmenu -i -p "SYSTEM: ")

if [ "$another" == "RELOAD" ] ; then
	xrdb -load ~/.Xdefaults; 
	i3-msg reload; 
	i3-msg restart;

elif [ "$another" == "LOCK" ] ; then
	exec betterlockscreen --lock

elif [ "$another" == "SUSPEND" ] ; then
	prompt "betterlockscreen --suspend" SUSPEND
		
elif [ "$another" == "LOGOUT" ] ; then
	prompt "i3-msg exit" LOGOUT
	
elif [ "$another" == "REBOOT" ] ; then
	prompt "reboot" REBOOT
	
elif [ "$another" == "POWEROFF" ] ; then
	prompt "poweroff" POWEROFF	

else
    echo $another
fi
