#!/usr/bin/bash

echo "Backing up dotfiles..."
cp ~/.vimrc ~/.backup/
cp ~/.bashrc ~/.backup/
cp ~/.dir_colors ~/.backup/
cp ~/.tmux.conf ~/.backup/
cp ~/.xinitrc ~/.backup/
cp ~/.eslintrc.js ~/.backup/
cp ~/.powerline-shell.json ~/.backup/

echo "Backing up Vim files..."
cp -r ~/.vim/ftplugin ~/.backup/.vim/
cp -r ~/.vim/snippets ~/.backup/.vim/

echo "Backing up configs..."
cp -r ~/.config/i3 ~/.backup/.config/
cp -r ~/.config/i3lock ~/.backup/.config/
cp -r ~/.config/rofi ~/.backup/.config/
cp -r ~/.config/compton ~/.backup/.config/
cp -r ~/.config/ranger ~/.backup/.config/
cp -r ~/.config/polybar ~/.backup/.config/
cp -r ~/.config/dunst ~/.backup/.config/
cp -r ~/.config/alacritty ~/.backup/.config/

echo "Backing up scripts..."
cp -r ~/.bin ~/.backup/

echo "Updating installed packages..."
pacman -Qqe > ~/.backup/pkglist.txt

echo "Uploading to GitHub"
(
cd ~/.backup && git add .
printf 'Commit Message: '
read -r commit
git commit -m "$commit"
git push origin master
)

echo "Done."
