#!/bin/bash

PYTHON_VENV="netzun-plus-backend"
SESSION_NAME="Netzun"

function netzun-backend {
    Main="$HOME/Development/Netzun/netzun-plus-api/"
    Apps="$HOME/Development/Netzun/netzun-plus-api/netzun/"

    cd $Main
    tmux start-server
    tmux new-session -d -s $SESSION_NAME -n server
    cd $Apps
    tmux new-window -t $SESSION_NAME:2 -n src

    tmux select-window -t $SESSION_NAME:1
	tmux send-keys -t $SESSION_NAME:server "workon $PYTHON_VENV; clear" C-m
	tmux send-keys -t $SESSION_NAME:src "workon $PYTHON_VENV; clear" C-m
    tmux attach-session -t $SESSION_NAME
}

netzun-backend
