#!/usr/bin/bash

DEST="org.mpris.MediaPlayer2.spotify"
TO="/org/mpris/MediaPlayer2"
MEMB="org.mpris.MediaPlayer2.Player"

function get-metadata {
	dbus-send --print-reply --dest=$DEST $TO org.freedesktop.DBus.Properties.Get \
		string:"$MEMB" string:'Metadata'				\
		| grep -Ev "^method"							\
		| grep -Eo '("(.*)")|(\b[0-9][a-zA-Z0-9.]*\b)'	\
		| sed -E '2~2 a|'								\
		| tr -d '\n'									\
		| sed -E 's/\|/\n/g'							\
		| sed -E 's/(xesam:)|(mpris:)//g'				\
		| sed -E 's/^"//'								\
		| sed -E 's/"$//'								\
		| sed -E 's/"+/|/'								\
		| sed -E 's/ +/ /g'
}

# Prints info about currently playing track.
function sp-current {
	get-metadata \
		| grep --color=never -E "(title)|(album)|(artist)" \
		| sed 's/^\(.\)/\U\1/'
}

CURR=$(sp-current)

#ALBUM=$(echo "$CURR" | grep -m 1 Album  | cut -d '|' -f2)
ARTIST=$(echo "$CURR" | grep -m 1 Artist | cut -d '|' -f2)
SONG=$(echo "$CURR" | grep -m 1 Title  | cut -d '|' -f2)

echo "$SONG - $ARTIST" # - $ALBUM"
