#!/bin/bash

name=$1
cmd=$2
exists=false
current_session=$(tmux ls | awk -F: '{print $1}')

tmux if-shell "tmux select-window -t $current_session:$name" "split-window -h" "new-window -t $current_session -n $name"

tmux send-keys -t $current_session:$name "$2" C-m

echo $exists
