#!/bin/bash
# Simple TaskWarrior frontend with Rofi.
# Piero Marini

ROFI_OPTIONS=(-theme $HOME/.config/rofi/side_bar -m -1 -thread 1 -dmenu -i -p "todo's: ")

e=$(task)

# TODO: Implement "task $id done" on selected.
todos=$(echo "${e}" | sed '/^\s*$/d' | sed '/^[0-9]* tasks$/d' | sed '/^--/d');
echo "${todos}"| rofi "${ROFI_OPTIONS[@]}";
