#!/bin/bash

function vue-dev {

    tmux start-server
    tmux new-session -d -s Vue -n Entry
    tmux new-window -t Vue:2 -n Components
    tmux new-window -t Vue:3 -n Server

    tmux select-window -t Vue:1
    tmux attach-session -t Vue
}

vue-dev
