#!/bin/bash

SESSION_NAME="Mps"

function work {
    Main="$HOME/Work/"

    cd $Main
    tmux start-server
    tmux new-session -d -s $SESSION_NAME -n main

    tmux select-window -t $SESSION_NAME:1
    tmux attach-session -t $SESSION_NAME
}

work
