#!/usr/bin/env bash

ICON=$HOME/.config/i3lock/icons/lock.png
TMPBG=/tmp/screen.png

sleep 0.4
scrot /tmp/screen.png
convert $TMPBG -scale 10% -scale 1000% $TMPBG
convert $TMPBG -filter Gaussian -blur 0x8 $TMPBG
convert $TMPBG $ICON -gravity center -composite -matte $TMPBG
# TODO: Stop using -u. Work on a good visual indicator.
i3lock -u -i $TMPBG
rm /tmp/screen.png
