#!/bin/bash

# Autostart
killall -q picom
while pgrep -x picom >/dev/null; do sleep 1; done
picom -b --config ~/.config/picom/picom.conf &

killall -q dunst
killall -q notify-osd
while pgrep -x dunst >/dev/null; do sleep 1; done
while pgrep -x notify-osd >/dev/null; do sleep 1; done
dunst -config ~/.config/dunst/dunst &

killall -q sxhkd
while pgrep -x sxhkd >/dev/null; do sleep 1; done

# Input Handler
sxhkd &

# Normal cursor
xsetroot -cursor_name left_ptr &

# Background
feh --bg-fill ~/Pictures/Wallpapers/chuttersnap-kuala-lumpur-unsplash.jpg

# TODO: Fix locker
# xautolock -time 20 -detectsleep -locker "betterlockscreen --lock" &

# Workspaces
# NOTE: This distributes 10 workspaces evenly amongst all connected monitors
i=1
n=`bspc query -M | wc -l`
per=$(( 11 / n ))
for monitor in `bspc query -M`; do
    bspc monitor $monitor -d `seq $i $(( i + per - 1 ))` 
    i=$(( i + per ))
done

# Polybar
bash /home/piero/.config/polybar/launch.sh &

bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"

bspc config presel_feedback_color "$color1"
bspc config presel_border_color "$color1"

bspc config focus_follows_pointer true
bspc config pointer_follows_focus false

bspc config pointer_modifier mod4 # super
bspc config pointer_action1 move
bspc config pointer_action2 resize_side

# Spacing
bspc config border_width 1
bspc config window_gap  10

bspc config bottom_padding	0
bspc config top_padding	40

bspc config split_ratio 0.50
bspc config gapless_monocle false
bspc config click_to_focus any

# Rules
bspc rule -a 'Brave-browser' desktop='2' follow=on
bspc rule -a Spotify desktop='4'
bspc rule -a Zathura desktop='3' state=tiled follow=on
bspc rule -a 'Primal Engine' state=floating
