#! /bin/bash

feh --bg-fill ~/Pictures/Wallpapers/chuttersnap-unsplash.jpg

sh /home/piero/.config/polybar/launch.sh &
xautolock -time 20 -detectsleep -locker "betterlockscreen --lock" &
xsetroot -cursor_name left_ptr &

# Workspaces
bspc monitor -d 1 2 3 4 5 6 7 8 9 10

# Colors
. "${HOME}/.xrdb/colors"

# Set the border colors
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"

bspc config presel_feedback_color "$color1"
bspc config presel_border_color "$color1"

# Borders and Gaps
bspc config border_radius       5
bspc config border_width        1
bspc config window_gap          10

bspc config bottom_padding		0
bspc config top_padding			10

bspc config split_ratio         0.50
bspc config gapless_monocle     false
bspc config click_to_focus      true

# Rules
bspc rule -a Chromium desktop="2"
bspc rule -a chromium desktop="2"
bspc rule -a spotify desktop="4"
