#!/bin/bash

# Kill everything
killall -q picom
while pgrep -x picom >/dev/null; do sleep 1; done

killall -q dunst
killall -q notify-osd
while pgrep -x dunst >/dev/null; do sleep 1; done
while pgrep -x notify-osd >/dev/null; do sleep 1; done

killall -q sxhkd
while pgrep -x sxhkd >/dev/null; do sleep 1; done

# Normal cursor
xsetroot -cursor_name left_ptr &

# Background
feh --bg-fill ~/Pictures/Wallpapers/patrick-baum-iQjVXncVfbg-unsplash.jpg

# TODO: Fix locker
# xautolock -time 20 -detectsleep -locker "betterlockscreen --lock" &

# Workspaces
# NOTE: This distributes 10 workspaces evenly amongst all connected monitors
i=1
n=`bspc query -M | wc -l`
per=$(( 11 / n ))
for monitor in `bspc query -M`; do
    bspc monitor $monitor -d `seq $i $(( i + per - 1 ))` 
    i=$(( i + per ))
done

bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"

bspc config presel_feedback_color "$color1"
bspc config presel_border_color "$color1"

bspc config focus_follows_pointer true
bspc config pointer_follows_focus false

bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

bspc config pointer_modifier mod4 # super
bspc config pointer_action1 move
bspc config pointer_action2 resize_side

# Spacing
bspc config border_width 1
bspc config window_gap  10

bspc config bottom_padding	0
bspc config top_padding	40
bspc config left_padding 7
bspc config right_padding 7

bspc config split_ratio 0.50
bspc config gapless_monocle false
bspc config click_to_focus any

# Rules
bspc rule -a 'Brave-browser' desktop='2' follow=on
bspc rule -a Spotify desktop='4'
bspc rule -a Zathura desktop='3' state=tiled follow=on
bspc rule -a zoom desktop='5' state=tiled follow=on
bspc rule -a Steam desktop='7' state=tiled follow=off
bspc rule -a discord desktop='8' state=tiled follow=off

# Temp rules
bspc rule -a 'Primal Engine' state=floating
bspc rule -a 'Proyecto 2' state=floating

# Init
bash /home/piero/.config/polybar/launch.sh &
picom -b --config ~/.config/picom/picom.conf &
dunst -config ~/.config/dunst/dunstrc &
sxhkd &
