#!/usr/bin/bash

echo "Backing up dotfiles..."
cp ~/.vimrc ~/.backup/vimrc
cp ~/.bashrc ~/.backup/bashrc
cp ~/.dir_colors ~/.backup/dir_colors
cp ~/.tmux.conf ~/.backup/tmux.conf

echo "Backing up Vim files..."
cp ~/.vim/ftplugin/*.vim ~/.backup/vim/ftplugin/
cp ~/.vim/snippets/* ~/.backup/vim/snippets/

echo "Backing up configs..."
cp ~/.config/termite/config ~/.backup/config/termite/
cp ~/.powerline-shell.json ~/.backup/powerline-shell.json

echo "Backing up scripts..."
cp ~/scripts/udev.bash ~/.backup/scripts/
cp ~/scripts/work.bash ~/.backup/scripts/
cp /usr/bin/backup ~/.backup/scripts/

echo "Updating installed packages..."
pacman -Qqe > ~/.backup/pkglist.txt

echo "Uploading to GitHub"
(
cd ~/.backup && git add .
printf 'Commit Message: '
read -r commit
git commit -m "$commit"
git push origin master
)

echo "Done."
