#!/bin/bash

ROFI_OPTIONS=(-theme /home/piero/.config/rofi/system)

if [ -z "$2" ] ; then
	ask="run $1"
else
    ask=$2
fi

prompt=$(echo -e "Yes\nNo" | rofi "${ROFI_OPTIONS[@]}" -dmenu -i -p "Are you sure you want to $ask?")

if [ "$prompt" == "Yes" ] ; then
	if [ "$1" == "sudo" ] ; then
		cat /home/piero/.scripts/askpass | sudo -S $2
	else
		$1
	fi
else
    echo $ask
fi
